# --- Core ---
vo=gpu-next
gpu-api=vulkan
hwdec=vaapi
audio-buffer=0.5
# --- Sync ---
video-sync=audio
opengl-glfinish=yes

# --- Quality ---
profile=fast

# --- Debanding ---
deband=yes
deband-iterations=2
deband-threshold=28

# --- Misc ---
keep-open=yes
save-position-on-quit=yes
